from enum import Enum


class Crime(Enum):
    BOMB_THREAT = "Bomb Threat"
    HOMICIDE = "Homicide"
    SEX_OFFENCE = "Sex Offence"
    INDECENT_ACT = "Indecent Act"
    THREATENING = "Threatening"
    ASSAULT = "Assault"
    ABDUCTION = "Abduction"
    ROBBERY = "Robbery"
    EXTORTION = "Extortion"
    BREAK_ENTER = "Break and Enter"
    THEFT = "Theft"
    VEHICLE_THEFT = "Vehicle Theft"
    BICYCLE_THEFT = "Bicycle Theft"
    WEAPON = "Weapon"
    PROPERTY_DAMAGE = "Property Damage"
    PROSTITUTION = "Prostitution"
    GAMBLING = "Gambling"
    DRUGS = "Drugs"
    MISSING_PERSON = "Missing Person"
    DISTURBANCE = "Disturbance"
    DISPUTE = "Dispute"
    DOMESTIC_DISPUTE = "Domestic Dispute"
    INTOXICATED = "Public Intoxication"
    MISCHIEF = "Public Mischief"
    SUSPICIOUS = "Suspicious Person"
    VEHICLE_COLLISION = "Vehicle Collision"
    HIT_RUN = "Hit and Run"
    IMPAIRED_DRIVER = "Impaired Driver"
    LIQUOR_OFFENCE = "Liquor Offence"
    ANIMAL_COMPLAINT = "Animal Complaint"
    HUMAN_TRAFFICKING = "Human Trafficking"
    HARASSMENT = "Harassment"
    INTERNET_CRIME = "Internet Crime"
    GRAFFITI = "Graffiti"
    BYLAW = "Bylaw Violation"
